package com.enzow.PeopleManagement.domain;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotEmpty;
import lombok.Data;

import java.io.Serializable;

/**
 * JPA entity that represent a Person in the system
 * This class is mapped to the 'persona' table in the MySQL DB
 * It includes autogenerated id, and the necessary data to create a Persona object to be saved in the DB
 * It is serialized by the implementation of {@link Serializable}
 *
 * The {@link Data} Lombok annotation automatically generates the getters, setters, toString, equals and hashCode methods
 */
@Data
@Entity
@Table(name = "persona")
public class Persona implements Serializable {

    /**
     * SerialVersionUID = 1L ensures that even a change in the class, java can still recognize and deserialize objects serialized with the previous version
     */
    private static final long serialVersionUID = 1L;

    /**
     * Unique identifier of a Persona Object automatically generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idpersona;

    /**
     * Attribute 'nombre' = Person's first name
     * Can't be empty (is validated in the form)
     */
    @NotEmpty
    private String nombre;

    /**
     * Attribute 'apellido' = Person's last name
     * Can't be empty (is validated in the form)
     */
    @NotEmpty
    private String apellido;

    /**
     * Attribute 'email' = Person's mail address
     * Can't be empty and needs proper format (is validated in the form)
     */
    @NotEmpty
    @Email
    private String email;

    /**
     * Attribute 'telefono' = Person's phone number
     * Is an optional field (is NOT validated in the form)
     */
    private String telefono;
}

