package com.enzow.PeopleManagement.domain;

import jakarta.persistence.*;
import lombok.Data;
import jakarta.validation.constraints.NotEmpty;

import java.io.Serializable;

/**
 * JPA entity that represent a User's rol in the system
 * This class is mapped to the 'rol' table in the MySQL DB
 * It includes autogenerated id, and the name of the user to be saved in the DB
 * It is serialized by the implementation of {@link Serializable}
 *
 * The roles are used to control access to specific functionalities within the app (ADMIN or USER)
 *
 * The {@link Data} Lombok annotation automatically generates the getters, setters, toString, equals and hashCode methods
 */
@Entity
@Data
@Table(name="rol")
public class Rol implements Serializable {

    /**
     * SerialVersionUID = 1L ensures that even a change in the class, java can still recognize and deserialize objects serialized with the previous version
     */
    private static final long serialVersionUID = 1L;

    /**
     * Unique identifier of a Persona Object automatically generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)//autoincremental en BD
    private Long id_rol;

    /**
     * Attribute 'nombre' = Person's first name
     * Can't be empty
     */
    @NotEmpty
    private String nombre;

}
